@extends('layouts.dashboard')

@section('title', 'Laporan')
@section('header', 'Laporan')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Laporan laundry</h1><p class="page-subtitle">Rekap transaksi dan pendapatan berdasarkan periode.</p></div><div class="flex gap-2"><a href="{{ route($role.'.reports.export', array_merge(request()->query(), ['format'=>'csv'])) }}" class="btn-secondary">Export CSV</a><a href="{{ route($role.'.reports.export', request()->query()) }}" target="_blank" class="btn-primary">Export PDF</a></div></div>
<form method="GET" action="{{ route($role.'.reports.index') }}" class="card mb-6 grid gap-4 p-5 sm:grid-cols-2 lg:grid-cols-5"><div><label class="form-label" for="period">Periode</label><select id="period" name="period" class="form-input"><option value="harian" @selected($period === 'harian')>Harian</option><option value="mingguan" @selected($period === 'mingguan')>Mingguan</option><option value="bulanan" @selected($period === 'bulanan')>Bulanan</option></select></div><div><label class="form-label" for="from">Dari tanggal</label><input id="from" type="date" name="from" value="{{ $from->format('Y-m-d') }}" class="form-input"></div><div><label class="form-label" for="to">Sampai tanggal</label><input id="to" type="date" name="to" value="{{ $to->format('Y-m-d') }}" class="form-input"></div><div><label class="form-label" for="status">Status laundry</label><select id="status" name="status" class="form-input"><option value="">Semua status</option>@foreach(\App\Enums\LaundryStatus::cases() as $item)<option value="{{ $item->value }}" @selected(request('status') === $item->value)>{{ $item->label() }}</option>@endforeach</select></div><div class="flex items-end"><button class="btn-primary w-full">Terapkan laporan</button></div></form>
<div class="grid gap-4 sm:grid-cols-3"><x-stat-card label="Jumlah transaksi" :value="$transactions->count()" description="Pada periode terpilih" icon="▤" tone="blue"/><x-stat-card label="Transaksi lunas" :value="$paidTransactions->count()" description="Sudah terverifikasi" icon="✓" tone="green"/><x-stat-card label="Pendapatan" :value="'Rp'.number_format($revenue, 0, ',', '.')" description="Total tagihan lunas" icon="Rp" tone="orange"/></div>
@if($role === 'admin')<div class="card mt-6 overflow-hidden"><div class="border-b border-slate-100 px-5 py-5"><h2 class="font-bold text-slate-900">Rekap per karyawan</h2><p class="mt-1 text-xs text-slate-400">Transaksi dan pendapatan yang ditugaskan</p></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Karyawan</th><th>Jabatan</th><th>Transaksi</th><th>Pendapatan</th></tr></thead><tbody>@foreach($employeeRecap as $recap)<tr><td class="font-semibold text-slate-800">{{ $recap['employee']->nama_lengkap }}</td><td>{{ $recap['employee']->posisi_jabatan }}</td><td>{{ $recap['count'] }}</td><td class="font-semibold text-brand-600">Rp{{ number_format($recap['revenue'], 0, ',', '.') }}</td></tr>@endforeach @if($employeeRecap->isEmpty())<tr><td colspan="4" class="py-8 text-center text-slate-400">Belum ada data karyawan.</td></tr>@endif</tbody></table></div></div>@endif
<div class="card table-wrap mt-6"><div class="border-b border-slate-100 px-5 py-5"><h2 class="font-bold text-slate-900">Rincian transaksi</h2><p class="mt-1 text-xs text-slate-400">{{ $from->format('d M Y') }} — {{ $to->format('d M Y') }}</p></div><table class="data-table"><thead><tr><th>Kode</th><th>Tanggal</th><th>Pelanggan</th><th>Layanan</th><th>Total</th><th>Status</th><th>Pembayaran</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr><td class="font-semibold text-brand-700">{{ $transaction->kode_transaksi }}</td><td>{{ $transaction->tanggal_masuk->format('d M Y') }}</td><td>{{ $transaction->user->nama_lengkap }}</td><td>{{ $transaction->layanan->nama_layanan }}</td><td class="font-semibold">Rp{{ number_format((float) $transaction->total_harga, 0, ',', '.') }}</td><td><x-status-badge :status="$transaction->status_laundry"/></td><td><x-status-badge :status="$transaction->status_pembayaran"/></td></tr>@empty<tr><td colspan="7" class="py-12 text-center text-slate-400">Tidak ada transaksi pada periode ini.</td></tr>@endforelse</tbody></table></div>
@endsection
