@extends('layouts.dashboard')

@section('title', 'Tambah Karyawan')
@section('header', 'Tambah karyawan')

@section('content')
@php($selectedPosition = old('posisi_jabatan', ''))
<div class="mb-8"><a href="{{ route('admin.karyawan.index') }}" class="text-sm font-semibold text-brand-600">← Kembali ke karyawan</a><h1 class="page-title mt-3">Buat akun karyawan</h1><p class="page-subtitle">Karyawan dapat masuk ke area operasional setelah akun dibuat.</p></div><form method="POST" action="{{ route('admin.karyawan.store') }}" class="max-w-3xl">@csrf<div class="card p-6 sm:p-8"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="form-label" for="nama_lengkap">Nama lengkap</label><input id="nama_lengkap" name="nama_lengkap" value="{{ old('nama_lengkap') }}" class="form-input" required>@error('nama_lengkap')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="username">Username</label><input id="username" name="username" value="{{ old('username') }}" class="form-input" required>@error('username')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="no_hp">No. HP</label><input id="no_hp" name="no_hp" value="{{ old('no_hp') }}" class="form-input" required>@error('no_hp')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email') }}" class="form-input" required>@error('email')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="posisi_jabatan">Posisi/jabatan</label><select id="posisi_jabatan" name="posisi_jabatan" class="form-input" required><option value="" disabled @selected($selectedPosition === '')>Pilih posisi/jabatan</option>@foreach (\App\Models\Karyawan::POSITIONS as $position)<option value="{{ $position }}" @selected($selectedPosition === $position)>{{ $position }}</option>@endforeach</select>@error('posisi_jabatan')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password">Password</label><input id="password" type="password" name="password" class="form-input" required>@error('password')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password_confirmation">Konfirmasi password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-input" required></div></div><div class="mt-7 flex justify-end gap-3"><a href="{{ route('admin.karyawan.index') }}" class="btn-secondary">Batal</a><button class="btn-primary">Buat akun karyawan</button></div></div></form>
@endsection
