@extends('layouts.dashboard')

@section('title', 'Edit Karyawan')
@section('header', 'Edit karyawan')

@section('content')
@php($selectedPosition = old('posisi_jabatan', $karyawan->posisi_jabatan))
<div class="mb-8"><a href="{{ route('admin.karyawan.index') }}" class="text-sm font-semibold text-brand-600">← Kembali ke karyawan</a><h1 class="page-title mt-3">Edit {{ $karyawan->nama_lengkap }}</h1><p class="page-subtitle">Perbarui informasi akun dan posisi karyawan.</p></div><form method="POST" action="{{ route('admin.karyawan.update', $karyawan) }}" class="max-w-3xl">@csrf @method('PUT')<div class="card p-6 sm:p-8"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="form-label" for="nama_lengkap">Nama lengkap</label><input id="nama_lengkap" name="nama_lengkap" value="{{ old('nama_lengkap', $karyawan->nama_lengkap) }}" class="form-input" required>@error('nama_lengkap')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="username">Username</label><input id="username" name="username" value="{{ old('username', $karyawan->username) }}" class="form-input" required>@error('username')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="no_hp">No. HP</label><input id="no_hp" name="no_hp" value="{{ old('no_hp', $karyawan->no_hp) }}" class="form-input" required>@error('no_hp')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="email">Email</label><input id="email" type="email" name="email" value="{{ old('email', $karyawan->email) }}" class="form-input" required>@error('email')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="posisi_jabatan">Posisi/jabatan</label><select id="posisi_jabatan" name="posisi_jabatan" class="form-input" required><option value="" disabled @selected($selectedPosition === '')>Pilih posisi/jabatan</option>@foreach (\App\Models\Karyawan::POSITIONS as $position)<option value="{{ $position }}" @selected($selectedPosition === $position)>{{ $position }}</option>@endforeach</select>@error('posisi_jabatan')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password">Password baru <span class="font-normal text-slate-400">(opsional)</span></label><input id="password" type="password" name="password" class="form-input">@error('password')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password_confirmation">Konfirmasi password</label><input id="password_confirmation" type="password" name="password_confirmation" class="form-input"></div></div><div class="mt-7 flex justify-end gap-3"><a href="{{ route('admin.karyawan.index') }}" class="btn-secondary">Batal</a><button class="btn-primary">Simpan perubahan</button></div></div></form>
@endsection
