@extends('layouts.dashboard')

@section('title', 'Pembayaran')
@section('header', 'Pembayaran')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Data pembayaran</h1><p class="page-subtitle">Verifikasi bukti pembayaran pelanggan.</p></div><div class="rounded-xl bg-brand-50 px-4 py-3 text-sm font-semibold text-brand-700">Total data: {{ $payments->total() }}</div></div>
<form method="GET" class="card mb-6 grid gap-3 p-4 sm:grid-cols-3"><div><label class="form-label" for="search">Cari</label><input id="search" name="search" value="{{ $search }}" class="form-input" placeholder="Kode atau nama pelanggan"></div><div><label class="form-label" for="status">Status</label><select id="status" name="status" class="form-input"><option value="">Semua status</option>@foreach(\App\Enums\PaymentStatus::cases() as $item)<option value="{{ $item->value }}" @selected($status === $item->value)>{{ $item->label() }}</option>@endforeach</select></div><div class="flex items-end"><button class="btn-primary w-full">Terapkan</button></div></form>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>ID</th><th>Kode transaksi</th><th>Pelanggan</th><th>Total tagihan</th><th>Jumlah bayar</th><th>Metode</th><th>Bukti</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td class="font-semibold text-slate-500">#{{ $payment->id }}</td><td class="font-semibold text-brand-700">{{ $payment->transaction->kode_transaksi }}</td><td>{{ $payment->transaction->user->nama_lengkap }}</td><td>Rp{{ number_format((float) $payment->transaction->total_harga, 0, ',', '.') }}</td><td class="font-semibold text-slate-800">Rp{{ number_format((float) $payment->jumlah_bayar, 0, ',', '.') }}</td><td>{{ $payment->metode->label() }}</td><td>@if($payment->bukti_pembayaran)<div class="flex items-center gap-2"><a href="{{ Storage::disk('public')->url($payment->bukti_pembayaran) }}" target="_blank" class="font-semibold text-brand-600">Preview</a>@if(in_array(pathinfo($payment->bukti_pembayaran, PATHINFO_EXTENSION), ['jpg', 'jpeg', 'png', 'webp'], true))<img src="{{ Storage::disk('public')->url($payment->bukti_pembayaran) }}" alt="Bukti pembayaran" class="h-10 w-10 rounded-lg object-cover ring-1 ring-slate-200">@endif</div>@else<span class="text-slate-400">—</span>@endif</td><td>{{ $payment->tanggal_bayar?->format('d M Y, H:i') ?? '—' }}</td><td><x-status-badge :status="$payment->status"/></td><td>@if($payment->status === \App\Enums\PaymentStatus::MenungguVerifikasi)<form method="POST" action="{{ route($role.'.payments.verify', $payment) }}">@csrf<button class="font-semibold text-emerald-600">Verifikasi</button></form>@else<span class="text-xs text-slate-400">Selesai</span>@endif</td></tr>@empty<tr><td colspan="10" class="py-14 text-center text-slate-400">Data pembayaran tidak ditemukan.</td></tr>@endforelse</tbody></table></div>@if($payments->hasPages())<div class="mt-5">{{ $payments->links() }}</div>@endif
@endsection
