@extends('layouts.dashboard')

@section('title', 'Edit Transaksi')
@section('header', 'Edit transaksi')

@section('content')
<div class="mb-8"><a href="{{ route($role.'.transactions.show', $transaction) }}" class="text-sm font-semibold text-brand-600">← Kembali ke detail</a><h1 class="page-title mt-3">Edit transaksi {{ $transaction->kode_transaksi }}</h1><p class="page-subtitle">Perbarui data operasional tanpa mengubah status laundry.</p></div>
<form method="POST" action="{{ route($role.'.transactions.update', $transaction) }}" class="max-w-3xl">@csrf @method('PUT')<div class="card p-6 sm:p-8"><div class="grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="form-label" for="layanan_id">Layanan</label><select id="layanan_id" name="layanan_id" class="form-input" required>@foreach($services as $service)<option value="{{ $service->id }}" @selected($transaction->layanan_id === $service->id)>{{ $service->nama_layanan }} · Rp{{ number_format((float) $service->harga_per_kg, 0, ',', '.') }}/{{ $service->satuan }}</option>@endforeach</select>@error('layanan_id')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="berat">Berat / jumlah</label><input id="berat" type="number" step="0.01" min="0.1" name="berat" value="{{ old('berat', $transaction->berat) }}" class="form-input" required>@error('berat')<p class="form-error">{{ $message }}</p>@enderror</div>@if($role === 'admin')<div><label class="form-label" for="karyawan_id">Karyawan</label><select id="karyawan_id" name="karyawan_id" class="form-input"><option value="">Belum ditugaskan</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" @selected($transaction->karyawan_id === $employee->id)>{{ $employee->nama_lengkap }}</option>@endforeach</select>@error('karyawan_id')<p class="form-error">{{ $message }}</p>@enderror</div>@else<div><span class="form-label">Karyawan</span><p class="form-input bg-slate-50">{{ $transaction->karyawan?->nama_lengkap ?? 'Belum ditugaskan' }}</p></div>@endif<div><label class="form-label" for="tanggal_masuk">Tanggal masuk</label><input id="tanggal_masuk" type="date" name="tanggal_masuk" value="{{ old('tanggal_masuk', $transaction->tanggal_masuk->format('Y-m-d')) }}" class="form-input" required>@error('tanggal_masuk')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="tanggal_estimasi_selesai">Estimasi selesai</label><input id="tanggal_estimasi_selesai" type="date" name="tanggal_estimasi_selesai" value="{{ old('tanggal_estimasi_selesai', $transaction->tanggal_estimasi_selesai->format('Y-m-d')) }}" class="form-input" required>@error('tanggal_estimasi_selesai')<p class="form-error">{{ $message }}</p>@enderror</div><div class="sm:col-span-2"><label class="form-label" for="catatan">Catatan</label><textarea id="catatan" name="catatan" rows="4" class="form-input">{{ old('catatan', $transaction->catatan) }}</textarea>@error('catatan')<p class="form-error">{{ $message }}</p>@enderror</div></div><div class="mt-7 flex justify-end gap-3"><a href="{{ route($role.'.transactions.show', $transaction) }}" class="btn-secondary">Batal</a><button class="btn-primary">Simpan perubahan</button></div></div></form>
@endsection
