@extends('layouts.dashboard')

@section('title', 'Data Transaksi')
@section('header', 'Data transaksi')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Data transaksi</h1><p class="page-subtitle">Kelola, filter, dan perbarui progres seluruh pesanan laundry.</p></div></div>
<form method="GET" action="{{ route($role.'.transactions.index') }}" class="card mb-6 grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-5"><div class="lg:col-span-2"><label class="form-label" for="search">Cari transaksi</label><input id="search" name="search" value="{{ $search }}" class="form-input" placeholder="Kode, nama, atau no HP"></div><div><label class="form-label" for="status">Status laundry</label><select id="status" name="status" class="form-input"><option value="">Semua status</option>@foreach(\App\Enums\LaundryStatus::cases() as $item)<option value="{{ $item->value }}" @selected($status === $item->value)>{{ $item->label() }}</option>@endforeach</select></div><div><label class="form-label" for="payment_status">Status bayar</label><select id="payment_status" name="payment_status" class="form-input"><option value="">Semua pembayaran</option>@foreach(\App\Enums\PaymentStatus::cases() as $item)<option value="{{ $item->value }}" @selected($paymentStatus === $item->value)>{{ $item->label() }}</option>@endforeach</select></div><div class="flex items-end"><button class="btn-primary w-full">Terapkan filter</button></div></form>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Tanggal masuk</th><th>Layanan</th><th>Berat</th><th>Total</th><th>Status laundry</th><th>Bayar</th><th>Aksi</th></tr></thead><tbody>@forelse($transactions as $transaction)<tr><td class="font-semibold text-brand-700">{{ $transaction->kode_transaksi }}</td><td><span class="block font-semibold text-slate-800">{{ $transaction->user->nama_lengkap }}</span><span class="text-xs text-slate-400">{{ $transaction->user->no_hp }}</span></td><td>{{ $transaction->tanggal_masuk->format('d M Y') }}</td><td>{{ $transaction->layanan->nama_layanan }}</td><td>{{ (float) $transaction->berat }} {{ $transaction->layanan->satuan }}</td><td class="font-semibold text-slate-800">Rp{{ number_format((float) $transaction->total_harga, 0, ',', '.') }}</td><td><x-status-badge :status="$transaction->status_laundry"/></td><td><x-status-badge :status="$transaction->status_pembayaran"/></td><td><div class="flex items-center gap-3"><a href="{{ route($role.'.transactions.show', $transaction) }}" class="font-semibold text-brand-600">Detail</a><a href="{{ route($role.'.transactions.edit', $transaction) }}" class="font-semibold text-slate-500">Edit</a></div></td></tr>@empty<tr><td colspan="9" class="py-14 text-center text-slate-400">Data transaksi tidak ditemukan.</td></tr>@endforelse</tbody></table></div>@if($transactions->hasPages())<div class="mt-5">{{ $transactions->links() }}</div>@endif
@endsection
