@extends('layouts.dashboard')

@section('title', 'Dashboard')
@section('header', 'Dashboard')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-brand-600">Selamat datang, {{ $staffUser->nama_lengkap }} 👋</p><h1 class="page-title mt-1">Ringkasan operasional</h1><p class="page-subtitle">Pantau aktivitas Laundry Go secara real-time.</p></div><a href="{{ route($role.'.transactions.index') }}" class="btn-primary">Lihat transaksi</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="Pesanan masuk hari ini" :value="$stats['todayTransactions']" description="Transaksi tanggal masuk hari ini" icon="↙" tone="orange"/><x-stat-card label="Menunggu" :value="$stats['waiting']" description="Perlu segera diproses" icon="◷" tone="slate"/><x-stat-card label="Diproses" :value="$stats['processing']" description="Sedang dikerjakan" icon="↻" tone="blue"/><x-stat-card label="Selesai" :value="$stats['completed']" description="Selesai & diambil" icon="✓" tone="green"/></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="Total pelanggan" :value="$stats['customers']" description="Terdaftar di sistem" icon="♙" tone="purple"/><x-stat-card label="Pendapatan hari ini" :value="'Rp'.number_format($stats['revenueToday'], 0, ',', '.')" description="Pembayaran terverifikasi" icon="Rp" tone="green"/><x-stat-card label="Total pendapatan" :value="'Rp'.number_format($stats['revenue'], 0, ',', '.')" description="Sepanjang waktu" icon="↗" tone="orange"/><x-stat-card label="Rating rata-rata" :value="number_format($stats['averageRating'], 1, ',', '.')" description="Dari seluruh ulasan" icon="★" tone="blue"/></div>
@if($role === 'admin')<div class="mt-4"><x-stat-card label="Jumlah karyawan" :value="$stats['employees']" description="Akun operasional aktif" icon="♟" tone="slate"/></div>@endif
<div class="mt-6 card table-wrap"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-5"><div><h2 class="font-bold text-slate-900">Transaksi terbaru</h2><p class="mt-1 text-xs text-slate-400">8 transaksi terakhir</p></div><a href="{{ route($role.'.transactions.index') }}" class="text-sm font-semibold text-brand-600">Kelola transaksi →</a></div><table class="data-table"><thead><tr><th>Kode</th><th>Pelanggan</th><th>Layanan</th><th>Tanggal</th><th>Total</th><th>Status</th></tr></thead><tbody>@forelse($recentTransactions as $transaction)<tr><td class="font-semibold text-slate-800">{{ $transaction->kode_transaksi }}</td><td>{{ $transaction->user->nama_lengkap }}</td><td>{{ $transaction->layanan->nama_layanan }}</td><td>{{ $transaction->tanggal_masuk->format('d M Y') }}</td><td class="font-semibold text-slate-800">Rp{{ number_format((float) $transaction->total_harga, 0, ',', '.') }}</td><td><x-status-badge :status="$transaction->status_laundry"/></td></tr>@empty<tr><td colspan="6" class="py-10 text-center text-slate-400">Belum ada transaksi.</td></tr>@endforelse</tbody></table></div>
@endsection
