<?php $__env->startSection('title', 'Data Pelanggan'); ?>
<?php $__env->startSection('header', 'Data pelanggan'); ?>

<?php $__env->startSection('content'); ?>
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Data pelanggan</h1><p class="page-subtitle">Kelola akun pelanggan Laundry Go.</p></div><a href="<?php echo e(route($role.'.customers.create')); ?>" class="btn-primary">＋ Tambah pelanggan</a></div>
<form method="GET" action="<?php echo e(route($role.'.customers.index')); ?>" class="card mb-6 flex flex-col gap-3 p-4 sm:flex-row"><div class="flex-1"><label class="form-label" for="search">Cari pelanggan</label><input id="search" name="search" value="<?php echo e($search); ?>" class="form-input" placeholder="Nama, username, email, atau no HP"></div><div class="flex items-end"><button class="btn-primary w-full sm:w-auto">Cari</button></div></form>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>Nama pelanggan</th><th>Username</th><th>No. HP</th><th>Email</th><th>Transaksi</th><th>Bergabung</th><th>Aksi</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $customers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $customer): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><span class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-brand-100 text-xs font-bold text-brand-700"><?php echo e(strtoupper(substr($customer->nama_lengkap, 0, 1))); ?></span><span class="font-semibold text-slate-800"><?php echo e($customer->nama_lengkap); ?></span></span></td><td><?php echo e($customer->username); ?></td><td><?php echo e($customer->no_hp); ?></td><td><?php echo e($customer->email); ?></td><td><?php echo e($customer->transactions_count); ?></td><td><?php echo e($customer->created_at->format('d M Y')); ?></td><td><div class="flex items-center gap-3"><a href="<?php echo e(route($role.'.customers.show', $customer)); ?>" class="font-semibold text-brand-600">Detail</a><a href="<?php echo e(route($role.'.customers.edit', $customer)); ?>" class="font-semibold text-slate-500">Edit</a><form method="POST" action="<?php echo e(route($role.'.customers.destroy', $customer)); ?>" onsubmit="return confirm('Hapus pelanggan ini?')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="font-semibold text-red-600">Hapus</button></form></div></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="7" class="py-14 text-center text-slate-400">Pelanggan tidak ditemukan.</td></tr><?php endif; ?></tbody></table></div><?php if($customers->hasPages()): ?><div class="mt-5"><?php echo e($customers->links()); ?></div><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('layouts.dashboard', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH /home/notfuad/ngodingweb/www/laundry-go/resources/views/staff/customers/index.blade.php ENDPATH**/ ?>