@extends('layouts.dashboard')

@section('title', 'Data Pelanggan')
@section('header', 'Data pelanggan')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Data pelanggan</h1><p class="page-subtitle">Kelola akun pelanggan Laundry Go.</p></div><a href="{{ route($role.'.customers.create') }}" class="btn-primary">＋ Tambah pelanggan</a></div>
<form method="GET" class="card mb-6 flex flex-col gap-3 p-4 sm:flex-row"><div class="flex-1"><label class="form-label" for="search">Cari pelanggan</label><input id="search" name="search" value="{{ $search }}" class="form-input" placeholder="Nama, username, email, atau no HP"></div><div class="flex items-end"><button class="btn-primary w-full sm:w-auto">Cari</button></div></form>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>Nama pelanggan</th><th>Username</th><th>No. HP</th><th>Email</th><th>Transaksi</th><th>Bergabung</th><th>Aksi</th></tr></thead><tbody>@forelse($customers as $customer)<tr><td><span class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-brand-100 text-xs font-bold text-brand-700">{{ strtoupper(substr($customer->nama_lengkap, 0, 1)) }}</span><span class="font-semibold text-slate-800">{{ $customer->nama_lengkap }}</span></span></td><td>{{ $customer->username }}</td><td>{{ $customer->no_hp }}</td><td>{{ $customer->email }}</td><td>{{ $customer->transactions_count }}</td><td>{{ $customer->created_at->format('d M Y') }}</td><td><div class="flex items-center gap-3"><a href="{{ route($role.'.customers.show', $customer) }}" class="font-semibold text-brand-600">Detail</a><a href="{{ route($role.'.customers.edit', $customer) }}" class="font-semibold text-slate-500">Edit</a><form method="POST" action="{{ route($role.'.customers.destroy', $customer) }}" onsubmit="return confirm('Hapus pelanggan ini?')">@csrf @method('DELETE')<button class="font-semibold text-red-600">Hapus</button></form></div></td></tr>@empty<tr><td colspan="7" class="py-14 text-center text-slate-400">Pelanggan tidak ditemukan.</td></tr>@endforelse</tbody></table></div>@if($customers->hasPages())<div class="mt-5">{{ $customers->links() }}</div>@endif
@endsection
