@extends('layouts.customer')

@section('title', 'Dashboard')
@section('header', 'Dashboard')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-brand-600">Halo, {{ $user->nama_lengkap }} 👋</p><h1 class="page-title mt-1">Ringkasan laundry Anda</h1><p class="page-subtitle">Pantau pesanan dan aktivitas laundry Anda di satu tempat.</p></div><a href="{{ route('customer.orders.create') }}" class="btn-primary">＋ Pesan laundry</a></div>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-stat-card label="Pesanan aktif" :value="$activeCount" description="Menunggu & diproses" icon="↻" tone="orange"/><x-stat-card label="Pesanan selesai" :value="$completedCount" description="Selesai & diambil" icon="✓" tone="green"/><x-stat-card label="Total pesanan" :value="$transactions->count()" description="Sepanjang waktu" icon="▤" tone="blue"/><x-stat-card label="Total pembayaran" :value="'Rp'.number_format($paidTotal, 0, ',', '.')" description="Transaksi lunas" icon="Rp" tone="purple"/></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><div class="card overflow-hidden xl:col-span-2"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-5"><div><h2 class="font-bold text-slate-900">Pesanan terbaru</h2><p class="mt-1 text-xs text-slate-400">Status laundry terakhir</p></div><a href="{{ route('customer.orders.index') }}" class="text-sm font-semibold text-brand-600 hover:text-brand-700">Lihat semua →</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Kode</th><th>Layanan</th><th>Status</th><th>Pembayaran</th><th></th></tr></thead><tbody>@forelse ($transactions->take(5) as $transaction)<tr><td class="font-semibold text-slate-800">{{ $transaction->kode_transaksi }}</td><td>{{ $transaction->layanan->nama_layanan }}</td><td><x-status-badge :status="$transaction->status_laundry"/></td><td><x-status-badge :status="$transaction->status_pembayaran"/></td><td><a href="{{ route('customer.orders.show', $transaction) }}" class="font-semibold text-brand-600">Detail</a></td></tr>@empty<tr><td colspan="5" class="py-10 text-center text-slate-400">Belum ada pesanan. Yuk mulai laundry!</td></tr>@endforelse</tbody></table></div></div><div class="space-y-6"><div class="card p-5"><div class="flex items-center justify-between"><h2 class="font-bold text-slate-900">Status laundry terbaru</h2><span class="text-brand-500">●</span></div>@if ($latestTransaction)<p class="mt-4 text-sm font-semibold text-slate-800">{{ $latestTransaction->kode_transaksi }} · {{ $latestTransaction->layanan->nama_layanan }}</p><div class="mt-3"><x-status-badge :status="$latestTransaction->status_laundry"/></div><p class="mt-3 text-xs text-slate-400">Diperbarui {{ $latestTransaction->updated_at->diffForHumans() }}</p>@else<p class="mt-3 text-sm text-slate-400">Belum ada aktivitas.</p>@endif</div><div class="card p-5"><h2 class="font-bold text-slate-900">Status pembayaran terbaru</h2>@if ($latestPayment)<p class="mt-4 text-sm font-semibold text-slate-800">{{ $latestPayment->payment->jumlah_bayar ? 'Rp'.number_format((float) $latestPayment->payment->jumlah_bayar, 0, ',', '.') : 'Belum ada pembayaran' }}</p><div class="mt-3"><x-status-badge :status="$latestPayment->status_pembayaran"/></div>@else<p class="mt-3 text-sm text-slate-400">Belum ada pembayaran.</p>@endif</div><div class="card p-5"><h2 class="font-bold text-slate-900">Rating terakhir</h2>@if ($latestReview && $latestReview->review)<p class="mt-3 text-2xl text-brand-500">{{ str_repeat('★', $latestReview->review->bintang) }}<span class="text-slate-200">{{ str_repeat('★', 5 - $latestReview->review->bintang) }}</span></p><p class="mt-2 text-sm text-slate-500">{{ $latestReview->review->ulasan ?: 'Terima kasih atas ulasan Anda.' }}</p>@else<p class="mt-3 text-sm text-slate-400">Beri rating setelah pesanan selesai.</p>@endif</div></div></div>
@endsection
