@extends('layouts.app')

@section('title', 'Beranda')

@section('content')
<section class="overflow-hidden bg-white">
    <div class="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-24">
        <div>
            <span class="inline-flex items-center gap-2 rounded-full bg-brand-100 px-3 py-1.5 text-xs font-bold text-brand-800">✦ Laundry modern untuk rutinitas Anda</span>
            <h1 class="mt-6 max-w-xl text-4xl font-extrabold leading-tight tracking-tight text-brand-900 sm:text-5xl">Cuci, rapi, <span class="text-brand-500">bikin hari lebih ringan.</span></h1>
            <p class="mt-5 max-w-lg text-base leading-7 text-slate-500 sm:text-lg">Pesan laundry tanpa repot datang ke outlet. Kami ambil, cuci, dan setrika dengan standar higienis—sampai siap dipakai lagi.</p>
            <div class="mt-8 flex flex-col gap-3 sm:flex-row"><a href="{{ auth('web')->check() ? route('customer.orders.create') : route('register') }}" class="btn-primary px-6 py-3">Pesan laundry sekarang <span>→</span></a><a href="{{ route('layanan') }}" class="btn-secondary px-6 py-3">Lihat layanan</a></div>
            <div class="mt-9 flex flex-wrap gap-6 text-sm text-slate-500"><span class="flex items-center gap-2"><b class="text-brand-500">✓</b> Tanpa minimum</span><span class="flex items-center gap-2"><b class="text-brand-500">✓</b> Tracking transparan</span><span class="flex items-center gap-2"><b class="text-brand-500">✓</b> Higienis terjamin</span></div>
        </div>
        <div class="relative mx-auto w-full max-w-lg">
            <div class="absolute -inset-5 rounded-[2.5rem] bg-brand-100/70 blur-2xl"></div>
            <div class="relative overflow-hidden rounded-[2rem] bg-brand-900 p-7 text-white shadow-2xl sm:p-10">
                <div class="flex items-start justify-between"><div><p class="text-sm font-semibold text-brand-300">LAUNDRY GO</p><p class="mt-2 text-2xl font-bold">Pantau pesanan<br>tanpa ribet.</p></div><span class="rounded-2xl bg-white/10 p-3 text-2xl">🧺</span></div>
                <div class="mt-10 rounded-2xl bg-white p-5 text-slate-800 shadow-xl"><div class="flex items-center justify-between"><div><p class="text-xs font-semibold uppercase tracking-wide text-slate-400">Status laundry</p><p class="mt-1 font-bold">LG-0001 · Cuci Komplit</p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-700">Selesai</span></div><div class="mt-5 flex items-center gap-2 text-xs text-slate-400"><span class="h-2 flex-1 rounded-full bg-brand-500"></span><span class="h-2 flex-1 rounded-full bg-brand-500"></span><span class="h-2 flex-1 rounded-full bg-brand-500"></span></div><div class="mt-3 flex justify-between text-[10px] font-semibold text-slate-400"><span>Menunggu</span><span>Diproses</span><span>Selesai</span></div></div>
                <div class="mt-5 grid grid-cols-2 gap-3"><div class="rounded-2xl bg-white/10 p-4"><p class="text-xs text-brand-200">Estimasi selesai</p><p class="mt-1 font-bold">Besok, 16:00</p></div><div class="rounded-2xl bg-white/10 p-4"><p class="text-xs text-brand-200">Poin laundry</p><p class="mt-1 font-bold text-brand-300">+120 poin</p></div></div>
            </div>
        </div>
    </div>
</section>
<section class="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
    <div class="grid gap-6 sm:grid-cols-3"><div class="card p-6"><span class="text-2xl">⚡</span><h3 class="mt-4 font-bold">Cepat & praktis</h3><p class="mt-2 text-sm leading-6 text-slate-500">Pesan dalam hitungan menit, tanpa antre di outlet.</p></div><div class="card p-6"><span class="text-2xl">♻️</span><h3 class="mt-4 font-bold">Higienis terjamin</h3><p class="mt-2 text-sm leading-6 text-slate-500">Peralatan dicuci dan dibersihkan untuk setiap pesanan.</p></div><div class="card p-6"><span class="text-2xl">💛</span><h3 class="mt-4 font-bold">Harga transparan</h3><p class="mt-2 text-sm leading-6 text-slate-500">Tarif jelas sesuai satuan, tanpa biaya tersembunyi.</p></div></div>
</section>
<section class="bg-brand-500 py-10 text-white"><div class="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-4 sm:px-6 md:flex-row md:items-center lg:px-8"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-brand-100">Promo pelanggan baru</p><h2 class="mt-1 text-2xl font-bold">Cuci pertama, hemat 10%!</h2><p class="mt-1 text-sm text-brand-50">Tunjukkan akun Laundry Go Anda saat banter ke outlet.</p></div><a href="{{ auth('web')->check() ? route('customer.orders.create') : route('register') }}" class="inline-flex items-center justify-center rounded-xl bg-white px-5 py-3 text-sm font-bold text-brand-700 shadow-sm transition hover:bg-brand-50">Klaim promo →</a></div></section>
<section class="bg-slate-50 py-16"><div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-brand-600">Katalog populer</p><h2 class="mt-2 text-3xl font-bold tracking-tight text-brand-900">Layanan yang kami siapkan</h2></div><a href="{{ route('layanan') }}" class="font-semibold text-brand-600 hover:text-brand-700">Lihat semua →</a></div><div class="mt-8 grid gap-5 md:grid-cols-3">@foreach ($layanan->take(3) as $service)<a href="{{ route('layanan') }}" class="card group p-6 transition hover:-translate-y-1 hover:border-brand-300"><div class="flex items-center justify-between"><span class="rounded-xl bg-brand-100 p-3 text-xl">✦</span><span class="text-xs font-semibold text-slate-400">{{ $service->estimasi_hari }} hari</span></div><h3 class="mt-5 font-bold text-brand-900 group-hover:text-brand-600">{{ $service->nama_layanan }}</h3><p class="mt-2 line-clamp-2 text-sm text-slate-500">{{ $service->deskripsi }}</p><p class="mt-5 font-bold text-brand-600">Rp{{ number_format((float) $service->harga_per_kg, 0, ',', '.') }}<span class="text-xs font-medium text-slate-400">/{{ $service->satuan }}</span></p></a>@endforeach</div></div></section>
<section class="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:px-8"><div><p class="text-sm font-bold uppercase tracking-[0.2em] text-brand-600">Kunjungi kami</p><h2 class="mt-2 text-3xl font-bold text-brand-900">Siap datang, kami temani.</h2><p class="mt-4 max-w-md text-sm leading-7 text-slate-500">Tim kami siap membantu setiap hari. Datang membawa laundry, atau pesan online dari mana saja.</p></div><div class="card p-6"><div class="space-y-4 text-sm"><p class="flex gap-3"><span class="text-brand-500">⌖</span><span><b class="block text-slate-800">Alamat</b><span class="text-slate-500">Jl. Raya Laundry No. 12, Jakarta</span></span></p><p class="flex gap-3"><span class="text-brand-500">◷</span><span><b class="block text-slate-800">Jam operasional</b><span class="text-slate-500">Senin–Sabtu, 08:00–20:00</span></span></p><p class="flex gap-3"><span class="text-brand-500">☎</span><span><b class="block text-slate-800">Hubungi kami</b><a class="text-brand-600" href="tel:+6281234567890">+62 812-3456-7890</a></span></p></div></div></section>
@endsection
