@extends('layouts.customer')

@section('title', 'Pesanan Saya')
@section('header', 'Pesanan saya')

@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="page-title">Pesanan saya</h1><p class="page-subtitle">Semua transaksi laundry yang pernah Anda buat.</p></div><a href="{{ route('customer.orders.create') }}" class="btn-primary">＋ Pesan laundry</a></div>
<div class="card table-wrap"><table class="data-table"><thead><tr><th>Kode transaksi</th><th>Tanggal</th><th>Layanan</th><th>Berat</th><th>Total harga</th><th>Status laundry</th><th>Status pembayaran</th><th>Aksi</th></tr></thead><tbody>@forelse ($transactions as $transaction)<tr><td class="font-semibold text-slate-800">{{ $transaction->kode_transaksi }}</td><td>{{ $transaction->tanggal_masuk->format('d M Y') }}</td><td>{{ $transaction->layanan->nama_layanan }}</td><td>{{ rtrim(rtrim(number_format((float) $transaction->berat, 2, ',', '.'), '0'), ',') }} {{ $transaction->layanan->satuan }}</td><td class="font-semibold text-slate-800">Rp{{ number_format((float) $transaction->total_harga, 0, ',', '.') }}</td><td><x-status-badge :status="$transaction->status_laundry"/></td><td><x-status-badge :status="$transaction->status_pembayaran"/></td><td><div class="flex items-center gap-3"><a href="{{ route('customer.orders.show', $transaction) }}" class="font-semibold text-brand-600">Detail</a>@if ($transaction->status_pembayaran === \App\Enums\PaymentStatus::BelumDibayar)<a href="{{ route('customer.payments.show', $transaction) }}" class="font-semibold text-emerald-600">Bayar</a>@endif @if ($transaction->canBeReviewed())<a href="{{ route('customer.reviews.create', $transaction) }}" class="font-semibold text-violet-600">Rating</a>@endif</div></td></tr>@empty<tr><td colspan="8" class="py-14 text-center"><p class="font-semibold text-slate-600">Belum ada pesanan.</p><a href="{{ route('customer.orders.create') }}" class="mt-2 inline-block text-sm font-semibold text-brand-600">Mulai pesan laundry →</a></td></tr>@endforelse</tbody></table></div>@if ($transactions->hasPages())<div class="mt-5">{{ $transactions->links() }}</div>@endif
@endsection
