@extends('layouts.customer')

@section('title', 'Profil Saya')
@section('header', 'Profil saya')

@section('content')
<div class="mb-8"><h1 class="page-title">Profil saya</h1><p class="page-subtitle">Kelola informasi akun dan keamanan Anda.</p></div>
<div class="grid gap-6 lg:grid-cols-2"><form method="POST" action="{{ route('customer.profile.update') }}" class="card p-6">@csrf<div class="flex items-center gap-4 border-b border-slate-100 pb-5"><span class="flex h-14 w-14 items-center justify-center rounded-full bg-brand-100 text-xl font-bold text-brand-700">{{ strtoupper(substr($user->nama_lengkap, 0, 1)) }}</span><div><h2 class="font-bold text-slate-900">{{ $user->nama_lengkap }}</h2><p class="text-sm text-slate-500">{{ $user->poin }} poin laundry</p></div></div><h3 class="mt-6 font-bold text-slate-900">Informasi akun</h3><div class="mt-4 space-y-4"><div><label class="form-label" for="nama_lengkap">Nama lengkap</label><input class="form-input" id="nama_lengkap" name="nama_lengkap" value="{{ old('nama_lengkap', $user->nama_lengkap) }}" required>@error('nama_lengkap')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="username">Username</label><input class="form-input" id="username" name="username" value="{{ old('username', $user->username) }}" required>@error('username')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="email">Email</label><input class="form-input" id="email" type="email" name="email" value="{{ old('email', $user->email) }}" required>@error('email')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="no_hp">No. HP</label><input class="form-input" id="no_hp" name="no_hp" value="{{ old('no_hp', $user->no_hp) }}" required>@error('no_hp')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="alamat">Alamat</label><textarea class="form-input" id="alamat" name="alamat" rows="3" required>{{ old('alamat', $user->alamat) }}</textarea>@error('alamat')<p class="form-error">{{ $message }}</p>@enderror</div></div><button class="btn-primary mt-6">Simpan perubahan</button></form><form method="POST" action="{{ route('customer.profile.password') }}" class="card h-fit p-6">@csrf<h2 class="font-bold text-slate-900">Ganti password</h2><p class="mt-2 text-sm text-slate-500">Gunakan password minimal 8 karakter.</p><div class="mt-5 space-y-4"><div><label class="form-label" for="password_lama">Password lama</label><input class="form-input" id="password_lama" type="password" name="password_lama" required>@error('password_lama')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password">Password baru</label><input class="form-input" id="password" type="password" name="password" required>@error('password')<p class="form-error">{{ $message }}</p>@enderror</div><div><label class="form-label" for="password_confirmation">Konfirmasi password baru</label><input class="form-input" id="password_confirmation" type="password" name="password_confirmation" required></div></div><button class="btn-secondary mt-6">Perbarui password</button></form></div>
@endsection
